### ISSUE TITLE
Annotation files

### ISSUE THREAD

**Issue by tamarahdez7** [zhwm/SparsePro_gw#1]
Hi 

I would like to generate an annotation file as your example for my data:
 SNP	Conserved_LindbladToh	DHS_Trynka	H3K27ac_Hnisz	H3K4me3_Trynka	Transcr_Hoffman	TSS_Hoffman	UTR_3_UCSC	UTR_5_UCSC	non_synonymous	Human_Promoter_Villar_ExAC
rs138862362	0	1	1	0	1	0	0	0	0	0
rs190750807	0	0	1	0	1	0	0	0	0	0

How could this be done?

Thank you in advance
Best wishes

**Comment by zhwm** [comment]
Hi,

You can generate the example annotation matrix using pybedtools (https://daler.github.io/pybedtools/).

Thanks!
